(function CarsServiceInit() {
    'use strict';

    angular.module('services')
        .factory('cars', CarsService);

    CarsService.$inject = ['_'];

    function CarsService(_) {

        var cars={
            'Acura':{
                'CL':['1996','1997','1998','1999','2000','2001','2002','2003'],
                'CSX':[''],
                'EL':[''],
                'ILX':[''],
                'Integra':[''],
                'Legend':[''],
                'MDX':[''],
                'NSX':[''],
                'RDX':[''],
                'RL':[''],
                'RLX':[''],
                'RSX':[''],
                'SLX':[''],
                'TL':[''],
                'TLX':[''],
                'TSX':[''],
                'ZDX':['']
            },
            'Alfa Romeo':{
                '105/115':[''],
                '145':[''],
                '146':[''],
                '147':[''],
                '155':[''],
                '159':[''],
                '164':[''],
                '166':[''],
                '1900':[''],
                '2600':[''],
                '33':[''],
                '4C':[''],
                '6':[''],
                '6C':[''],
                '75':[''],
                '8C Competizione':[''],
                '90':[''],
                'Alfasud':[''],
                'Alfetta':[''],
                'Arna':[''],
                'Brera':[''],
                'Disco Volante':[''],
                'Giulia':[''],
                'Giulietta':[''],
                'GT':[''],
                'GTA Coupe':[''],
                'GTV':[''],
                'MiTo':[''],
                'Montreal':[''],
                'RZ':[''],
                'Spider':[''],
                'Sprint':[''],
                'SZ':['']
            },
            'Alpina':{
                'B10':[''],
                'B11':[''],
                'B12':[''],
                'B3':[''],
                'B4':[''],
                'B5':[''],
                'B6':[''],
                'B7':[''],
                'B8':[''],
                'B9':[''],
                'C1':[''],
                'C2':[''],
                'D10':[''],
                'D3':[''],
                'D5':[''],
                'Roadster':[''],
                'XD3':['']
            },
            'Aston Martin':{
                'Bulldog':[''],
                'Cygnet':[''],
                'DB11':[''],
                'DB7':[''],
                'DB9':[''],
                'DBS':[''],
                'Lagonda':[''],
                'One-77':[''],
                'Rapide':[''],
                'Tickford Capri':[''],
                'V12 Vanquish':[''],
                'V12 Vantage':[''],
                'V12 Zagato':[''],
                'V8 Vantage':[''],
                'V8 Zagato':[''],
                'Virage':['']
            },
            'Audi': {
                '100':[''],
                '200':[''],
                '50':[''],
                '80':[''],
                '90':[''],
                '920':[''],
                'A1':[''],
                'A2':[''],
                'A3':[''],
                'A4':[''],
                'A4 allroad':[''],
                'A5':[''],
                'A6':[''],
                'A6 allroad':[''],
                'A7':[''],
                'A8':[''],
                'Cabriolet':[''],
                'Coupe':[''],
                'Q2':[''],
                'Q3':[''],
                'Q5':[''],
                'Q7':[''],
                'quattro':[''],
                'R8':[''],
                'RS Q3':[''],
                'RS2':[''],
                'RS3':[''],
                'RS4':[''],
                'RS5':[''],
                'RS6':[''],
                'RS7':[''],
                'S1':[''],
                'S2':[''],
                'S3':[''],
                'S4':[''],
                'S5':[''],
                'S6':[''],
                'S7':[''],
                'S8':[''],
                'SQ5':[''],
                'SQ7':[''],
                'TT':[''],
                'TT RS':[''],
                'TTS':[''],
                'V8':['']
            },
            'Bentley':{
                'Arnage':[''],
                'Azure':[''],
                'Bentayga':[''],
                'Brooklands':[''],
                'Continental':[''],
                'Continental Flying Spur':[''],
                'Continental GT':[''],
                'Eight':[''],
                'Flying Spur':[''],
                'Mark 6':[''],
                'Mulsanne':[''],
                'R Type':[''],
                'S':[''],
                'T-Series':[''],
                'Turbo R':['']
            },
            'BMW':{
                '02(E10)':[''],
                '1er':[''],
                '1M':[''],
                '2er':[''],
                '321':[''],
                '327':[''],
                '340':[''],
                '3er':[''],
                '4er':[''],
                '5er':[''],
                '6er':[''],
                '7er':[''],
                '8er':[''],
                'i3':[''],
                'i8':[''],
                'M2':[''],
                'M3':[''],
                'M4':[''],
                'M5':[''],
                'M6':[''],
                'X1':[''],
                'X3':[''],
                'X4':[''],
                'X5':[''],
                'X5 M':[''],
                'X6':[''],
                'X6 M':[''],
                'Z1':[''],
                'Z3':[''],
                'Z3 M':[''],
                'Z4':[''],
                'Z4 M':[''],
                'Z8':['']
            },
            'Brilliance':{
                'FRV(BS2)':[''],
                'H530':[''],
                'M1 (BS6)':[''],
                'M2 (BS4)':[''],
                'M3 (BS3)':[''],
                'V5':['']
            },
            'Bugatti':{
                'Chiron':[''],
                'EB 110':[''],
                'EB 112':[''],
                'EB Veyron 16.4':['']
            },
            'BYD':{
                'F3':[''],
                'F5':[''],
                'F6':[''],
                'F8':[''],
                'Flyer':['']
            },
            'Cadillac':{
                'ATS':[''],
                'ATS-V':[''],
                'BLS':[''],
                'Brougham':[''],
                'Catera':[''],
                'CTS':[''],
                'CTS-V':[''],
                'De Ville':[''],
                'DTS':[''],
                'Eldorado':[''],
                'ELR':[''],
                'Escalade':[''],
                'Fleetwood':[''],
                'Seville':[''],
                'SRX':[''],
                'STS':[''],
                'XT5':['']
            },
            'Changam':{
                'Benni':[''],
                'CS35':[''],
                'Eado':[''],
                'Raeton':[''],
                'Z-Shine':['']
            },
            'Chery':{
                'Amulet':[''],
                'Arrizo 7':[''],
                'Bonus (A13)':[''],
                'Bonus 3':[''],
                'CrossEastar':[''],
                'Fora':[''],
                'IndiS':[''],
                'Kimo':[''],
                'M11':[''],
                'Oriental Son':[''],
                'QQ6':[''],
                'Sweet':[''],
                'Tiggo (T11)':[''],
                'Tiggo 5':[''],
                'Very (A13)':['']
            },
            'Chevrolet':{
                'Alero':[''],
                'Astro':[''],
                'Avalanche':[''],
                'Aveo':[''],
                'Bel Air':[''],
                'Beretta':[''],
                'Blazer':[''],
                'Blazer K5':[''],
                'C-10':[''],
                'Camaro':[''],
                'Caprice':[''],
                'Captiva':[''],
                'Cavalier':[''],
                'Chevette':[''],
                'Cobalt':[''],
                'Colorado':[''],
                'Corvette':[''],
                'Cruze':[''],
                'Cruze (HR)':[''],
                'Epica':[''],
                'Equinox':[''],
                'Evanda':[''],
                'Express':[''],
                'HHR':[''],
                'Impala':[''],
                'Lacetti':[''],
                'Lanos':[''],
                'Lumina':[''],
                'Lumina APV':[''],
                'Malibu':[''],
                'Metro':[''],
                'MW':[''],
                'Niva':[''],
                'Orlando':[''],
                'Prizm':[''],
                'Rezzo':[''],
                'S-10 Pickup':[''],
                'Silverado':[''],
                'Spark':[''],
                'SS':[''],
                'SSR':[''],
                'Starcraft':[''],
                'Suburban':[''],
                'Tahoe':[''],
                'Tavera':[''],
                'Tracker':[''],
                'TrailBlazer':[''],
                'Trans Sport':[''],
                'Van':[''],
                'Viva':[''],
                'Volt':['']
            },
            'Chrysler':{
                '180':[''],
                '200':[''],
                '300C':[''],
                '300C SRT8':[''],
                '300M':[''],
                'Cirrus':[''],
                'Concorde':[''],
                'Crossfire':[''],
                'Fifth Avenue':[''],
                'Imperial':[''],
                'Intrepid':[''],
                'Le Baron':[''],
                'LHS':[''],
                'Neon':[''],
                'New Yorker':[''],
                'Pacifica':[''],
                'Prowler':[''],
                'PT Cruiser':[''],
                'Saratoga':[''],
                'Sebring':[''],
                'Stratus':[''],
                'Town & Country':[''],
                'Vision':[''],
                'Voyager':['']
            },
            'Citroen':{
                '2 CV':[''],
                'Berlingo':[''],
                'BX':[''],
                'C-Crosser':[''],
                'C-Elysee':[''],
                'С1':[''],
                'С2':[''],
                'С3':[''],
                'C3 Picasso':[''],
                'C4':[''],
                'C4 Aircross':[''],
                'C4 Picasso':[''],
                'C5':[''],
                'C6':[''],
                'C8':[''],
                'CX':[''],
                'DS3':[''],
                'DS4':[''],
                'DS5':[''],
                'Evasion':[''],
                'GS':[''],
                'Jumpy':[''],
                'LN':[''],
                'Saxo':[''],
                'Xantia':[''],
                'XM':[''],
                'Xsara':[''],
                'Xsara Picasso':[''],
                'ZX':['']
            },
            'Daewoo':{
                'Arcadia':[''],
                'Chairman':[''],
                'Damas':[''],
                'Espero':[''],
                'Evanda':[''],
                'G2X':[''],
                'Gentra':[''],
                'Kalos':[''],
                'Korando':[''],
                'Lacetti':[''],
                'Lanos':[''],
                'Leganza':[''],
                'LeMans':[''],
                'Magnus':[''],
                'Matiz':[''],
                'Musso':[''],
                'Nexia':[''],
                'Nubira':[''],
                'Prince':[''],
                'Racer':[''],
                'Rezzo':[''],
                'Sens':[''],
                'Tacuma':[''],
                'Tico':[''],
                'Tosca':[''],
                'Winstorm':['']
            },
            'Daihatsu':{
                'Applause':[''],
                'Atrai':[''],
                'Be-go':[''],
                'Boon':[''],
                'Charade':[''],
                'Coo':[''],
                'Copen':[''],
                'Cuore':[''],
                'Esse':[''],
                'Feroza':[''],
                'Materia':[''],
                'MAX':[''],
                'Mira':[''],
                'Mira Gino':[''],
                'Move':[''],
                'Pyzar':[''],
                'Rocky':[''],
                'Sirion':[''],
                'Sonica':[''],
                'Storia':[''],
                'Tanto':[''],
                'Terios':[''],
                'Xenia':[''],
                'YRV':['']
            },
            'Datsun':{
                'mi-DO':[''],
                'on-DO':[''],
                'Urvan':['']
            },
            'Dodge':{
                'Aries':[''],
                'Avenger':[''],
                'Caliber':[''],
                'Caravan':[''],
                'Challenger':[''],
                'Charger':[''],
                'Dakota':[''],
                'Dart':[''],
                'Daytona':[''],
                'Durango':[''],
                'Dynasty':[''],
                'Intrepid':[''],
                'Journey':[''],
                'Magnum':[''],
                'Neon':[''],
                'Nitro':[''],
                'RAM':[''],
                'Spirit':[''],
                'Stealth':[''],
                'Stratus':[''],
                'Viper':['']
            },
            'DS':{
                '3':[''],
                '4':[''],
                '5':['']
            },
            'FAW':{
                'Besturn B50':[''],
                'Jinn':[''],
                'Oley':[''],
                'V2':[''],
                'V5':[''],
                'Vita':['']
            },
            'Ferrari':{
                '360':[''],
                '458':[''],
                '488':[''],
                '550':[''],
                '599':[''],
                '612':[''],
                'California':[''],
                'F12berlinetta':[''],
                'F430':[''],
                'FF':[''],
                'GTC4Lusso':[''],
                'Enzo':[''],
                'LaFerrari':['']
            },
            'Fiat':{
                '124 Sport Spider':[''],
                '126':[''],
                '500':[''],
                '600':[''],
                '900T':[''],
                'Albea':[''],
                'Brava':[''],
                'Bravo':[''],
                'Coupe':[''],
                'Croma':[''],
                'Doblo':[''],
                'Fiorino':[''],
                'Freemont':[''],
                'Fullback':[''],
                'Linea':[''],
                'Marea':[''],
                'Multipla':[''],
                'Palio':[''],
                'Panda':[''],
                'Punto':[''],
                'Qubo':[''],
                'Regata':[''],
                'Ritmo':[''],
                'Scudo':[''],
                'Sedici':[''],
                'Seicento':[''],
                'Siena':[''],
                'Stilo':[''],
                'Tempra':[''],
                'Tipo':[''],
                'Ulusse':[''],
                'Uno':['']
            },
            'Ford':{
                'Aerostar':[''],
                'Bronco':[''],
                'Bronco-2':[''],
                'C-MAX':[''],
                'Capri':[''],
                'Consul':[''],
                'Contour':[''],
                'Cougar':[''],
                'Crown Victoria':[''],
                'Custom':[''],
                'Econoline':[''],
                'EcoSport':[''],
                'Edge':[''],
                'Escape':[''],
                'Escort':[''],
                'Excursion':[''],
                'Expedition':[''],
                'Explorer':[''],
                'Explorer Sport Trac':[''],
                'F-150':[''],
                'Fiesta':[''],
                'Fiesta ST':[''],
                'Five Hundred':[''],
                'Focus':[''],
                'Focus RS':[''],
                'Focus ST':[''],
                'Freestyle':[''],
                'Fusion':[''],
                'Galaxie':[''],
                'Galaxy':[''],
                'Granada':[''],
                'KA':[''],
                'Kuga':[''],
                'Laser':[''],
                'LTD Crown Victoria':[''],
                'MAverick':[''],
                'Mondeo':[''],
                'Mondeo ST':[''],
                'Mustang':[''],
                'Orion':[''],
                'Probe':[''],
                'Puma':[''],
                'Ranchero':[''],
                'Ranger':[''],
                'S-MAX':[''],
                'Scorpio':[''],
                'Sierra':[''],
                'Spectron':[''],
                'Taunus':[''],
                'Taurus':[''],
                'Taurus X':[''],
                'Telstar':[''],
                'Tempo':[''],
                'Thunderbird':[''],
                'Tourneo Connect':[''],
                'Tourneo Custom':[''],
                'Windstar':[''],
                'Zephyr':['']
            },
            'GAZ':{
                '12 ЗИМ':[''],
                '13 "Чайка"':[''],
                '14 "Чайка"':[''],
                '21 "Волга"':[''],
                '22 "Волга"':[''],
                '24 "Волга"':[''],
                '2330 "Тигр"':[''],
                '3102 "Волга"':[''],
                '31029 "Волга"':[''],
                '3105 "Волга"':[''],
                '3110 "Волга"':[''],
                '31105 "Волга"':[''],
                '3111 "Волга"':[''],
                '67':[''],
                '69':[''],
                'Volga Siber':[''],
                'M-20 "Победа"':[''],
                'М-72':[''],
                'М1':['']
            },
            'Geely':{
                'CK (Otaka)':[''],
                'Emgrand 7':[''],
                'Emgrand EC7':[''],
                'Emgrand X7':[''],
                'FC (Vision)':[''],
                'GC6':[''],
                'MK':[''],
                'MK Cross':[''],
                'SC7':['']
            },
            'GMC':{
                'Acadia':[''],
                'Canyon':[''],
                'Envoy':[''],
                'Jimmy':[''],
                'Safari':[''],
                'Savana':[''],
                'Sierra':[''],
                'Suburban':[''],
                'Terrain':[''],
                'Typhoon':[''],
                'Vandura':[''],
                'Yukon':['']
            },
            'Great Wall':{
                'Coolbear':[''],
                'Cowry':[''],
                'Deer':[''],
                'Florid':[''],
                'Hover':[''],
                'Hover H3':[''],
                'Hover H5':[''],
                'Hover H6':[''],
                'Hover M2':[''],
                'Hover M4':[''],
                'Peri':[''],
                'Safe':[''],
                'Sailor':[''],
                'Sing RUV':[''],
                'Voleex C30':[''],
                'Wingle':['']
            },
            'Hafei':{
                'Brio':[''],
                'Princip':[''],
                'Simbo':['']
            },
            'Haima':{
                '3':[''],
                '7':[''],
                'M3':['']
            },
            'Haval':{
                'H2':[''],
                'H6':[''],
                'H8':[''],
                'H9':['']
            },
            'Hawtai':{
                'Boliger':['']
            },
            'Honda':{
                'Accord':[''],
                'Acty':[''],
                'Airwave':[''],
                'Ascot':[''],
                'Ascot Innova':[''],
                'Avancier':[''],
                'Beat':[''],
                'Capa':[''],
                'City':[''],
                'Civic':[''],
                'Civic Ferio':[''],
                'Civic Type R':[''],
                'Domani':[''],
                'Edix':[''],
                'Element':[''],
                'Elysion':[''],
                'Fit':[''],
                'Fit Aria':[''],
                'FR-V':[''],
                'Freed':[''],
                'HR-V':[''],
                'Insight':[''],
                'Inspire':[''],
                'Integra':[''],
                'Jazz':[''],
                'Legend':[''],
                'Life':[''],
                'Logo':[''],
                'Mobilio':[''],
                'NSX':[''],
                'Odyssey':[''],
                'Orthia':[''],
                'Partner':[''],
                'Pilot':[''],
                'Prelude':[''],
                'Rafaga':[''],
                'Ridgeline':[''],
                'S-MX':[''],
                'S2000':[''],
                'Saber':[''],
                'Shuttle':[''],
                'Stepwgn':[''],
                'Stream':[''],
                'Torneo':[''],
                'Vamos':[''],
                'Vezel':[''],
                'Vigor':[''],
                'Zest':['']
            },
            'Hummer':{
                'H1':[''],
                'H2':[''],
                'H3':['']
            },
            'Hyunday':{
                'Accent':[''],
                'Atos':[''],
                'Avante':[''],
                'Centennial':[''],
                'Coupe':[''],
                'Creta':[''],
                'Elantra':[''],
                'Equus':[''],
                'Excel':[''],
                'Galloper':[''],
                'Genesis':[''],
                'Genesis Coupe':[''],
                'Getz':[''],
                'Grace':[''],
                'Grandeur':[''],
                'i10':[''],
                'i20':[''],
                'i30':[''],
                'i40':[''],
                'ix20':[''],
                'ix35':[''],
                'ix55':[''],
                'Lantra':[''],
                'Lavita':[''],
                'Matrix':[''],
                'Maxcruz':[''],
                'Pony':[''],
                'Santa Fe':[''],
                'Santamo':[''],
                'Solaris':[''],
                'Sonata':[''],
                'Starex (H-1)':[''],
                'Terracan':[''],
                'Tiburon':[''],
                'Trajet':[''],
                'Tucson':[''],
                'Tuscani':[''],
                'Veloster':[''],
                'Veracruz':[''],
                'Verna':[''],
                'XG':['']
            },
            'Infiniti':{
                'EX':[''],
                'FX':[''],
                'G':[''],
                'I':[''],
                'J':[''],
                'JX':[''],
                'M':[''],
                'Q':[''],
                'Q50':[''],
                'Q70':[''],
                'QX30':[''],
                'QX4':[''],
                'QX50':[''],
                'QX56':[''],
                'QX60':[''],
                'QX70':[''],
                'QX80':['']
            },
            'JAC':{
                'J2':[''],
                'J5':[''],
                'M1':[''],
                'S1':[''],
                'S3':[''],
                'S5':['']
            },
            'Jaguar':{
                'E-type':[''],
                'F-Pace':[''],
                'F-type':[''],
                'S-Type':[''],
                'X-Type':[''],
                'XE':[''],
                'XF':[''],
                'XFR':[''],
                'XJ':[''],
                'XJR':[''],
                'XJS':[''],
                'XK':[''],
                'XKR':['']
            },
            'Jeep':{
                'Cherokee':[''],
                'CJ':[''],
                'Commander':[''],
                'Compass' :[''],
                'Grand Cherokee':[''],
                'Grand Cherokee SRT8':[''],
                'Liberty (North America)':[''],
                'Liberty (Patriot)':[''],            
                'Renegade':[''],
                'Wrangler':['']
            },
            'KIA':{
                'Avella':[''],
                'Cadenza':[''],
                'Capital':[''],
                'Carens':[''],
                'Carnival':[''],
                'Ceed':[''],
                'Ceed GT':[''],
                'Cerato':[''],
                'Clarus':[''],
                'Joice':[''],
                'Magentis':[''],
                'Mohave (Borrego)':[''],
                'Opirus':[''],
                'Optima':[''],
                'Picanto':[''],
                'Pride':[''],
                'Quoris':[''],
                'Retona':[''],
                'Rio':[''],
                'Sedona':[''],
                'Sephia':[''],
                'Shuma':[''],
                'Sorento':[''],
                'Soul':[''],
                'Spectra':[''],
                'Sportage':[''],
                'Venga':[''],
                'X-Trek':['']
            },
            'Lada':{
                '1111 Ока':[''],
                '2101':[''],
                '2102':[''],
                '2103':[''],
                '2104':[''],
                '2105':[''],
                '2106':[''],
                '2107':[''],
                '2108':[''],
                '2109':[''],
                '21099':[''],
                '2110':[''],
                '2111':[''],
                '2112':[''],
                '2113':[''],
                '2114':[''],
                '2115':[''],
                '2120 Надежда':[''],
                '2121 (4х4)':[''],
                '2123':[''],
                '2129':[''],
                '2131 (4х4)':[''],
                '2329':[''],
                'El Lada':[''],
                'Granta':[''],
                'Kalina':[''],
                'Largus':[''],
                'Priora':[''],
                'Vesta':[''],
                'XRAY':['']
            },
            'Lamborghini':{
                'Aventador':[''],
                'Centanario':[''],
                'Countach':[''],
                'Diablo':[''],
                'Gallardo':[''],
                'Huracan':[''],
                'LM001':[''],
                'LM002':[''],
                'Miura':[''],
                'Murcielago':[''],
                'Reventon':[''],
                'Sesto Elemento':[''],
                'Veneno':['']
            },
            'Land Rover':{
                'Defender':[''],
                'Discovery':[''],
                'Discovery Sport':[''],
                'Freelander':[''],
                'Range Rover':[''],
                'Range Rover Evogue':[''],
                'Range Rover Sport':['']
            },
            'Lexus':{
                'CT':[''],
                'ES':[''],
                'GS':[''],
                'GS F':[''],
                'GX':[''],
                'HS':[''],
                'IS':[''],
                'IS F':[''],
                'LS':[''],
                'LX':[''],
                'NX':[''],
                'RC':[''],
                'RX':[''],
                'SC':['']
            },
            'LIFAN':{
                'Breez':[''],
                'Cebrium':[''],
                'Celliya':[''],
                'Smily':[''],
                'Solano':[''],
                'X50':[''],
                'X60':['']
            },
            'Lincoln':{
                'Aviator':[''],
                'Capri':[''],
                'Continental':[''],
                'LS':[''],
                'Mark VII':[''],
                'Mark VIII':[''],
                'MKC':[''],
                'MKT':[''],
                'MKX':[''],
                'MKZ':[''],
                'Navigator':[''],
                'Town Car':['']
            },
            'Lotus':{
                'Eclat':[''],
                'Elan':[''],
                'Elise':[''],
                'Elite':[''],
                'Esprit':[''],
                'Europa':[''],
                'Europa S':[''],
                'Exide':['']
            },
            'Luxgen':{
                'Luxgen5':[''],
                'Luxgen7 MPV':[''],
                'Luxgen7 SUV':[''],
                'U7 Turbo':['']
            },
            'Marussia':{
                'B1':[''],
                'B2':['']
            },
            'Maserati':{
                '3200 GT':[''],
                '4200 GT':[''],
                'Biturbo':[''],
                'Ghibli':[''],
                'GranTurismo':[''],
                'Quattroporte':['']
            },
            'Maybach':{
                '57':[''],
                '62':['']
            },
            'Mazda':{
                '121':[''],
                '2':[''],
                '3':[''],
                '3 MPS':[''],
                '323':[''],
                '5':[''],
                '6':[''],
                '6 MPS':[''],
                '616':[''],
                '626':[''],
                '929':[''],
                'Atenza':[''],
                'Axela':[''],
                'AZ-Offroad':[''],
                'AZ-Wagon':[''],
                'B-series':[''],
                'Biante':[''],
                'Bongo':[''],
                'Bongo Friendee':[''],
                'BT-50':[''],
                'Capella':[''],
                'Carol':[''],
                'CX-3':[''],
                'CX-5':[''],
                'CX-7':[''],
                'CX-9':[''],
                'Demino':[''],
                'Efini MS-6':[''],
                'Efini MS-8':[''],
                'Eunos 500':[''],
                'Eunos 800':[''],
                'Eunos Cosmo':[''],
                'Familia':[''],
                'Lantis':[''],
                'Laputa':[''],
                'Millenia':[''],
                'MPV':[''],
                'MX-3':[''],
                'MX-5':[''],
                'MX-6':[''],
                'Premacy':[''],
                'Proceed Levante':[''],
                'Proceed Marvie':[''],
                'Protege':[''],
                'RX-7':[''],
                'RX-8':[''],
                'Tribute':[''],
                'Verisa':[''],
                'Xedos 6':[''],
                'Xedos 9':['']
            },
            'McLaren':{
                '650S':[''],
                'F1':[''],
                'MP4-12C':[''],
                'P1':['']
            },
            'Mercedes-Benz':{
                '190 (W201)':[''],
                '190 SL':[''],
                'A-klasse':[''],
                'A-klasse AMG':[''],
                'AMG GT':[''],
                'B-class':[''],
                'C-klasse':[''],
                'C-klasse AMG':[''],
                'Citan':[''],
                'CL-klasse':[''],
                'CL-klasse AMG':[''],
                'CLA-klasse':[''],
                'CLA-klasse AMG':[''],
                'CLC-klasse':[''],
                'CLK-klasse':[''],
                'CLK-klasse AMG':[''],
                'CLS-klasse':[''],
                'CLS-klasse AMG':[''],
                'E-klasse':[''],
                'E-klasse AMG':[''],
                'G-klasse':[''],
                'G-klasse AMG':[''],
                'G-klasse AMG 6x6':[''],
                'GL-klasse':[''],
                'GL-klasse AMG':[''],
                'GLA-klasse':[''],
                'GLA-klasse AMG':[''],
                'GLC':[''],
                'GLC AMG':[''],
                'GLC Coupe':[''],
                'GLC Coupe AMG':[''],
                'GLE':[''],
                'GLE AMG':[''],
                'GLE Coupe':[''],
                'GLE Coupe AMG':[''],
                'GLK-klasse':[''],
                'GLS-klasse':[''],
                'GLS-klasse AMG':[''],
                'M-klasse':[''],
                'M-klasse AMG':[''],
                'Maybach S-klasse':[''],
                'R-klasse':[''],
                'S-klasse':[''],
                'S-klasse AMG':[''],
                'SL-klasse':[''],
                'SL-klasse AMG':[''],
                'SLC-klasse':[''],
                'SLC-klasse AMG':[''],
                'SLK-klasse':[''],
                'SLK-klasse AMG':[''],
                'SLR McLaren':[''],
                'SLS AMG':[''],
                'V-klasse':[''],
                'Vaneo':[''],
                'Viano':[''],
                'Vito':[''],
                'W110':[''],
                'W111':[''],
                'W114':[''],
                'W115':[''],
                'W123':[''],
                'W124':[''],
                'W128':[''],
                'W186':['']
            },
            'MINI':{
                'Cabrio':[''],
                'Clubman':[''],
                'Countryman':[''],
                'Coupe':[''],
                'Hatch':[''],
                'Paceman':[''],
                'Roadster':['']
            },
            'Mitsubishi':{
                '3000 GT':[''],
                'Airtrek':[''],
                'Aspire':[''],
                'ASX':[''],
                'Carisma':[''],
                'Challenger':[''],
                'Chariot':[''],
                'Colt':[''],
                'Delica':[''],
                'Delica D:2':[''],
                'Diamante':[''],
                'Dingo':[''],
                'Dion':[''],
                'Eclipse':[''],
                'eK':[''],
                'Emeraude':[''],
                'Endeavor':[''],
                'Eterna':[''],
                'FTO':[''],
                'Galant':[''],
                'Grandis':[''],
                'GTO':[''],
                'i':[''],
                'i-MiEV':[''],
                'L200':[''],
                'Lancer':[''],
                'Lancer Cargo':[''],
                'Lancer Evolution':[''],
                'Lancer Ralliart':[''],
                'Legnum':[''],
                'Libero':[''],
                'Minica':[''],
                'Minicab':[''],
                'Mirage':[''],
                'Montero':[''],
                'Montеro Sport':[''],
                'Qutlander':[''],
                'Pajero':[''],
                'Pajero iO':[''],
                'Pajero Junior':[''],
                'Pajero Mini':[''],
                'Pajero Pinin':[''],
                'Pajero Sport':[''],
                'Raider':[''],
                'RVR':[''],
                'Sapporo':[''],
                'Sigma':[''],
                'Space Gear':[''],
                'Space Star':[''],
                'Space Runner':[''],
                'Space Wagon':[''],
                'Toppo':[''],
                'Town Box':['']
            },
            'Nissan':{
                '100NX':[''],
                '200SX':[''],
                '280ZX':[''],
                '300ZX':[''],
                '350Z':[''],
                '370Z':[''],
                'AD':[''],
                'Amera':[''],
                'Almera Classic':[''],
                'Almero Tino':[''],
                'Altima':[''],
                'Armada':[''],
                'Avenir':[''],
                'Bassara':[''],
                'Bluebird':[''],
                'BlueBird Sylphy':[''],
                'Caravan':[''],
                'Cedric':[''],
                'Cefiro':[''],
                'Cima':[''],
                'Clipper':[''],
                'Cube':[''],
                'Datsun':[''],
                'Dualis':[''],
                'Elgrand':[''],
                'Expert':[''],
                'Fairlady Z':[''],
                'Figaro':[''],
                'Fuga':[''],
                'Gloria':[''],
                'GT-R':[''],
                'Juke':[''],
                'Juke Nismo':[''],
                'Kix':[''],
                'Lafesta':[''],
                'Largo':[''],
                'Laruel':[''],
                'Leaf':[''],
                'Leopard':[''],
                'Liberty':[''],
                'Lucino':[''],
                'March':[''],
                'Maxima':[''],
                'Micra':[''],
                'Mistral':[''],
                'Moco':[''],
                'Murano':[''],
                'Navara (Frontier)':[''],
                'Note':[''],
                'NP 300':[''],
                'NV200':[''],
                'Otti (Dayz)':[''],
                'Pathfinder':[''],
                'Patrol':[''],
                'Pino':[''],
                'Pixo':[''],
                'Prairie':[''],
                'Presage':[''],
                'Presea':[''],
                'President':[''],
                'Primaster':[''],
                'Primera':[''],
                'Pulsar':[''],
                'Qashqai':[''],
                'Qashqai+2':[''],
                'Quest':[''],
                'Rnessa':[''],
                'Rasheen':[''],
                'Rogue':[''],
                'Roox':[''],
                'Safari':[''],
                'Sentra':[''],
                'Serena':[''],
                'Silvia':[''],
                'Skyline':[''],
                'Stagea':[''],
                'Stanza':[''],
                'Sunny':[''],
                'Teana':[''],
                'Terrano':[''],
                'Terrano Regulus':[''],
                'Tiida':[''],
                'Tino':[''],
                'Titan':[''],
                'Urvan':[''],
                'Vanette':[''],
                'Wingroad':[''],
                'X-Terra':[''],
                'X-Trail':['']
            },
            'Opel':{
                'Agila':[''],
                'Ampera':[''],
                'Antara':[''],
                'Asona':[''],
                'Astra':[''],
                'Astra OPC':[''],
                'Calibra':[''],
                'Combo':[''],
                'Commodore':[''],
                'Corsa':[''],
                'Corsa OPC':[''],
                'Frontera':[''],
                'Insignia':[''],
                'Insignia OPC':[''],
                'Kadett':[''],
                'Kapitan':[''],
                'Manta':[''],
                'Meriva':[''],
                'Mokka':[''],
                'Monterey':[''],
                'Olimpia':[''],
                'Omega':[''],
                'Record':[''],
                'Senator':[''],
                'Signum':[''],
                'Sintra':[''],
                'Tigra':[''],
                'Vectra':[''],
                'Vectra OPC':[''],
                'Vita':[''],
                'Vivaro':[''],
                'Zafira':['']
            },
            'Peugeot':{
                '1007':[''],
                '106':[''],
                '107':[''],
                '2008':[''],
                '206':[''],
                '207':[''],
                '208':[''],
                '3008':[''],
                '301':[''],
                '305':[''],
                '306':[''],
                '307':[''],
                '308':[''],
                '309':[''],
                '4007':[''],
                '4008':[''],
                '405':[''],
                '406':[''],
                '407':[''],
                '408':[''],
                '5008':[''],
                '508':[''],
                '605':[''],
                '607':[''],
                '806':[''],
                '807':[''],
                'Bipper':[''],
                'Expert':[''],
                'Partner':[''],
                'RCZ':['']
            },
            'PGO':{
                'Speedster II':['']
            },
            'Porsche':{
                '718 Boxter':[''],
                '718 Cayman':[''],
                '911':[''],
                '911 GT3':[''],
                '918 Spyder':[''],
                '924':[''],
                '928':[''],
                '944':[''],
                'Boxter':[''],
                'Carrera GT':[''],
                'Cayenne':[''],
                'Cayman':[''],
                'Cayman GT4':[''],
                'Macan':[''],
                'Panamera':['']
            },
            'Ravon':{
                'Gentra':[''],
                'Matiz':[''],
                'NexiaR3':[''],
                'R2':['']
            },
            'Renault':{
                '11':[''],
                '19':[''],
                '21':[''],
                '25':[''],
                '9':[''],
                'Captur':[''],
                'Clio':[''],
                'Clio RS':[''],
                'Dokker':[''],
                'Duster':[''],
                'Espace':[''],
                'Fluence':[''],
                'Fuego':[''],
                'Kangoo':[''],
                'Kaptur':[''],
                'Koleos':[''],
                'Laguna':[''],
                'Latitude':[''],
                'Lodgy':[''],
                'Logan':[''],
                'Megane':[''],
                'Megane RS':[''],
                'Modus':[''],
                'Safrane':[''],
                'Sandero':[''],
                'Scenic':[''],
                'Symbol':[''],
                'Trafic':[''],
                'Twingo':[''],
                'Twizy':[''],
                'Vel Satis':[''],
                'ZOE':['']
            },
            'Rolls-Royce':{
                '20/25':[''],
                'Corniche':[''],
                'Dawn':[''],
                'Ghost':[''],
                'Phantom':[''],
                'Silver Cloud':[''],
                'Silver Spur':[''],
                'Wraith':['']
            },
            'Saab':{
                '9-3':[''],
                '9-5':[''],
                '9-7X':[''],
                '900':[''],
                '9000':[''],
                '95':[''],
                '96':[''],
                '99':['']
            },
            'Seat':{
                'Alhambra':[''],
                'Altea':[''],
                'Arosa':[''],
                'Cordoba':[''],
                'Ibiza':[''],
                'Ibiza Cupra':[''],
                'Leon':[''],
                'Leon Cupra':[''],
                'Malaga':[''],
                'Marbella':[''],
                'Toledo':['']
            },
            'Skoda':{
                '100 Series':[''],
                'Fabia':[''],
                'Fabia RS':[''],
                'Favourit':[''],
                'Felicia':[''],
                'Octavia':[''],
                'Octavia RS':[''],
                'Rapid':[''],
                'Roomster':[''],
                'Superb':[''],
                'Yeti':['']
            },
            'Smart':{
                'Forfour':[''],
                'Fortwo':[''],
                'Roadster':['']
            },
            'SsangYong':{
                'Actyon':[''],
                'Actyon Sports':[''],
                'Korando':[''],
                'Korando Family':[''],
                'Kyron':[''],
                'Musso':[''],
                'Nomad':[''],
                'Rexton':[''],
                'Rodius':[''],
                'Stavic':[''],
                'Tivoli':['']
            },
            'Subaru':{
                'Baja':[''],
                'BRZ':[''],
                'Exiga':[''],
                'Forester':[''],
                'Impreza':[''],
                'Impreza WRX':[''],
                'Impreza WRX STi':[''],
                'Justy':[''],
                'Legacy':[''],
                'Leone':[''],
                'Outback':[''],
                'Pleo':[''],
                'R1':[''],
                'R2':[''],
                'Sambar':[''],
                'Stella':[''],
                'SVX':[''],
                'Traviq':[''],
                'Trezia':[''],
                'Tribeca':[''],
                'Vivio':[''],
                'WRX':[''],
                'WRX STi':[''],
                'XV':['']
            },
            'Suzuki':{
                'Aerio':[''],
                'Alto':[''],
                'Baleno':[''],
                'Cervo':[''],
                'Escudo':[''],
                'Every':[''],
                'Forenza':[''],
                'Grand Vitara':[''],
                'Ignis':[''],
                'Kei':[''],
                'Kizashi':[''],
                'Landy':[''],
                'Liana':[''],
                'MR Wagon':[''],
                'Palette':[''],
                'Samurai':[''],
                'Solio':[''],
                'Splash':[''],
                'Swift':[''],
                'SX4':[''],
                'Vitara':[''],
                'Wagon R':[''],
                'Wagon R+':[''],
                'XL7':['']
            },
            'TagAZ':{
                'Aquila':[''],
                'C-30':[''],
                'C10':[''],
                'C190':[''],
                'Road Partner':[''],
                'Tager':[''],
                'Vega':['']
            },
            'Tata':{
                'Indigo':[''],
                'Safari':[''],
                'Sumo':['']
            },
            'Tesla Motors':{
                'Model S':[''],
                'Model X':[''],
                'Roadster':['']
            },
            'Toyota':{
                '4Runner':[''],
                'Allex':[''],
                'Allion':[''],
                'Alphard':[''],
                'Altezza':[''],
                'Aqua':[''],
                'Aristo':[''],
                'Auris':[''],
                'Avalon':[''],
                'Avensis':[''],
                'Avensis Verso':[''],
                'Aygo':[''],
                'bB':[''],
                'Belta':[''],
                'Blade':[''],
                'Blizzard':[''],
                'Brevis':[''],
                'Caldina':[''],
                'Cami':[''],
                'Camry':[''],
                'Camry Solara':[''],
                'Carina':[''],
                'Carina ED':[''],
                'Cavalier':[''],
                'Celica':[''],
                'Celsior':[''],
                'Century':[''],
                'Chaser':[''],
                'Corolla':[''],
                'Corolla Rumion':[''],
                'Corolla Spacio':[''],
                'Corolla Verso':[''],
                'Corona':[''],
                'Corsa':[''],
                'Cresta':[''],
                'Crown':[''],
                'Crown Magesta':[''],
                'Curren':[''],
                'Cynos':[''],
                'Duet':[''],
                'Echo':[''],
                'Estima':[''],
                'FJ Cruiser':[''],
                'Fortuner':[''],
                'FunCargo':[''],
                'Gaia':[''],
                'Granvia':[''],
                'GT86':[''],
                'Harrier':[''],
                'HiAce':[''],
                'Highlander':[''],
                'Hilux':[''],
                'Hilux Surf':[''],
                'Ipsum':[''],
                'iQ':[''],
                'ISis':[''],
                'Ist':[''],
                'Kluger':[''],
                'Land Cruiser':[''],
                'Land Cruiser Prado':[''],
                'LiteAce':[''],
                'Mark 2':[''],
                'Mark X':[''],
                'MasterAce Surf':[''],
                'Matrix':[''],
                'Mega Cruiser':[''],
                'MR2':[''],
                'Nadia':[''],
                'Noach':[''],
                'Opa':[''],
                'Paseo':[''],
                'Passo':[''],
                'Passo Sette':[''],
                'Picnic':[''],
                'Platz':[''],
                'Porte':[''],
                'Premio':[''],
                'Previa':[''],
                'Prius':[''],
                'Probox':[''],
                'Progres':[''],
                'Ractis':[''],
                'Raum':[''],
                'RAV 4':[''],
                'Regius':[''],
                'RegiusAce':[''],
                'rush':[''],
                'Scepter':[''],
                'Sequonia':[''],
                'Sera':[''],
                'Sienna':[''],
                'Sienta':[''],
                'Soarer':[''],
                'Soluna':[''],
                'Sparky':[''],
                'Sprinter':[''],
                'Sprinter Carib':[''],
                'Sprinter Marino':[''],
                'Sprinter Trueno':[''],
                'Starlet':[''],
                'Succeed':[''],
                'Supra':[''],
                'Tacoma':[''],
                'Tercel':[''],
                'TownAce':[''],
                'Tundra':[''],
                'Urban Cruiser':[''],
                'Vanquard':[''],
                'Vellfire':[''],
                'Venza':[''],
                'Verossa':[''],
                'Verso':[''],
                'Vista':[''],
                'Vitz':[''],
                'Voltz':[''],
                'Voxy':[''],
                'WiLL':[''],
                'WiLL Cypha':[''],
                'Windom':[''],
                'Wish':[''],
                'Yaris':[''],
                'Yaris Verso':['']
            },
            'UAZ':{
                '3151':[''],
                '3153':[''],
                '3159':[''],
                '3160':[''],
                '3162 Simbir':[''],
                '469':[''],
                'Hunter':[''],
                'Patriot':[''],
                'Pickup':['']
            },
            'Volkswagen':{
                'Amarok':[''],
                'Beetle':[''],
                'Bora':[''],
                'Caddy':[''],
                'California':[''],
                'Caravelle':[''],
                'Corrado':[''],
                'Eos':[''],
                'Fox':[''],
                'Golf':[''],
                'Golf Country':[''],
                'Golf GTI':[''],
                'Golf Plus':[''],
                'Golf R':[''],
                'Golf R32':[''],
                'Iltis':[''],
                'Jetta':[''],
                'Lupo':[''],
                'Multivan':[''],
                'Passat':[''],
                'Passat CC':[''],
                'Phaeton':[''],
                'Pointer':[''],
                'Polo':[''],
                'Polo GTI':[''],
                'Routan':[''],
                'Santana':[''],
                'Scirocco':[''],
                'Scirocco R':[''],
                'Sharan':[''],
                'Tiguan':[''],
                'Touareg':[''],
                'Touran':[''],
                'Transporter':[''],
                'Type 1':[''],
                'Type 2':[''],
                'up!':[''],
                'Vento':['']
            },
            'Volvo':{
                '120 Series':[''],
                '240 Series':[''],
                '300 Series':[''],
                '440':[''],
                '460':[''],
                '480':[''],
                '740':[''],
                '760':[''],
                '850':[''],
                '940':[''],
                '960':[''],
                'C30':[''],
                'C70':[''],
                'Laplander':[''],
                'S40':[''],
                'S60':[''],
                'S60 Cross Country':[''],
                'S70':[''],
                'S80':[''],
                'S90':[''],
                'V40':[''],
                'V40 Cross Country':[''],
                'V50':[''],
                'V60':[''],
                'V60 Cross Country':[''],
                'V70':[''],
                'V90':[''],
                'XC60':[''],
                'XC70':[''],
                'XC90':['']
            },
            'ZAZ':{
                '1102 "Таврия"':[''],
                '1103 "Славута"':[''],
                '1105 "Дана"':[''],
                '965':[''],
                '966':[''],
                '968':[''],
                'Chance':[''],
                'Forza':[''],
                'Sens':[''],
                'Vida':['']
            },
            'Zotye':{
                'T600':[''],
                'Z100':[''],
                'Z300':['']
            },
            'ZXAuto':{
                'Grand Tiger':[''],
                'Landmark':['']
            },
            'Ё-авто':{
                'Ё-Кроссовер':['']
            }


        };
        return {  
            cars: cars,
        };


    }
})();